AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Simple Lambda for Contact Form Email

Resources:
  ContactFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          AWS_REGION: eu-west-1
      Events:
        ContactApi:
          Type: Api
          Properties:
            Path: /contact
            Method: post
