name: Detect backend changes
description: Detect changes in backend code

outputs:
  lambda:
    value: ${{ steps.changes.outputs.lambda }}

runs:
  using: composite
  steps:
    - name: Detect changes
      uses: dorny/paths-filter@v4
      id: changes
      with:
        filters: |
          lambda:
            - 'backend/src/**'
