name: Backend Deploy (PROD)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/src/**'
      - 'backend/package.json'
      - 'backend/scripts/build-lambda.js'
permissions:
  contents: read
  id-token: write

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Enable pnpm
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.13.0
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --filter backend
        shell: bash
        env:
          CI: true

      - name: Build lambda
        run: pnpm --filter backend run build:lambda contact-form
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-lambda-prod-role
          aws-region: eu-west-1

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name prod-contact-form-lambda \
            --zip-file fileb://backend/dist/contact-form.zip
