name: Backend Build & Deploy

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'backend/src/**'
      - 'backend/infra/**'
      - '!backend/**/*.md'

  pull_request:
    branches:
      - main
    paths:
      - 'backend/src/**'
      - 'backend/infra/**'
      - '!backend/**/*.md'
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  id-token: write

jobs:
  # ========================
  # DEV workflow (push to dev)
  # ========================
  dev:
    concurrency:
      group: terraform-dev
      cancel-in-progress: true
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup backend
        uses: ./.github/actions/setup-backend

      - name: Configure AWS credentials (dev)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-terraform-dev-role
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.5

      - name: Terraform Format
        run: terraform fmt -check -recursive backend/infra

      - name: Terraform Init (dev)
        working-directory: ./backend/infra/envs/dev
        run: terraform init

      - name: Terraform Validate
        working-directory: ./backend/infra/envs/dev
        run: terraform validate

      - name: Terraform Apply (dev)
        working-directory: ./backend/infra/envs/dev
        run: terraform apply -auto-approve

  # ========================
  # PLAN for PROD (PR → main)
  # ========================
  plan-prod:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup backend
        uses: ./.github/actions/setup-backend

      - name: Configure AWS credentials (prod)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-terraform-prod-role
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.5

      - name: Terraform Format
        run: terraform fmt -check -recursive backend/infra

      - name: Terraform Init (prod)
        working-directory: ./backend/infra/envs/prod
        run: terraform init

      - name: Terraform Validate
        working-directory: ./backend/infra/envs/prod
        run: terraform validate

      - name: Terraform Plan (prod)
        working-directory: ./backend/infra/envs/prod
        run: terraform plan

  # ========================
  # APPLY for PROD (push/merge → main)
  # ========================
  apply-prod:
    concurrency:
      group: terraform-prod
      cancel-in-progress: false
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production # manual approval in GitHub
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup backend
        uses: ./.github/actions/setup-backend

      - name: Configure AWS credentials (prod)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-terraform-prod-role
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.5

      - name: Terraform Format
        run: terraform fmt -check -recursive backend/infra

      - name: Terraform Init (prod)
        working-directory: ./backend/infra/envs/prod
        run: terraform init

      - name: Terraform Validate
        working-directory: ./backend/infra/envs/prod
        run: terraform validate

      - name: Terraform Apply (prod)
        working-directory: ./backend/infra/envs/prod
        run: terraform apply
