name: Backend Deploy (PROD)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/src/**'
      - 'backend/package.json'
      - 'pnpm-lock.yaml'
      - 'backend/scripts/build-lambda.js'
      - '!backend/**/*.md'
permissions:
  contents: read
  id-token: write

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build Lambdas
        uses: ./.github/actions/build-lambdas

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/prod-github-actions-lambda-deploy-role
          aws-region: eu-west-1

      - name: Deploy Lambdas
        run: |
          for zip in backend/dist/*.zip; do
            lambda_name=$(basename "$zip" .zip)
            aws_name="prod-${lambda_name}-lambda"

            echo "🚀 Deploying $lambda_name..."

            aws lambda update-function-code \
              --function-name "$aws_name" \
              --zip-file "fileb://$zip"
          done
