name: Frontend Deploy (DEV)

on:
  push:
    branches:
      - dev
    paths:
      - 'frontend/**'
      - '!frontend/**/*.md'
permissions:
  contents: read
  id-token: write

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Enable pnpm
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.13.0
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --filter frontend
        shell: bash
        env:
          CI: true

      - name: Build frontend
        run: pnpm --filter frontend run build
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/dev-github-actions-frontend-deploy-role
          aws-region: eu-west-1

      - name: Deploy to S3
        run: aws s3 sync frontend/dist s3://dev-portfolio-static-site --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.DEV_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
