name: Terraform Deploy (DEV)

on:
  push:
    branches:
      - dev
    paths:
      - 'infra/**'
      - 'backend/src/**'
      - 'backend/package.json'
      - 'pnpm-lock.yaml'
      - 'backend/scripts/build-lambda.js'
      - '!backend/**/*.md'

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/envs/dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/dev-github-actions-terraform-role
          aws-region: eu-west-1

      - name: Check for Lambda changes
        uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            lambda:
              - 'backend/src/**'
              - 'backend/package.json'
              - 'pnpm-lock.yaml'
              - 'backend/scripts/build-lambda.js'

      - name: Build Lambdas
        if: steps.changes.outputs.lambda == 'true'
        uses: ./.github/actions/build-lambdas

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
